# Generated by Django 4.1.1 on 2022-09-08 14:53

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=cpf_field.models.CPFField(max_length=14, verbose_name="cpf"),
        ),
    ]
