# Generated by Django 4.1.1 on 2022-09-09 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("zip_code", models.CharField(max_length=8)),
                ("address", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("complement", models.TextField(blank=True, null=True)),
                ("district", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("state", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
            ],
        ),
    ]
