# Generated by Django 4.1.1 on 2022-09-12 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quotation", models.DecimalField(decimal_places=2, max_digits=15)),
                ("transaction_date_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
