# Generated by Django 4.1.1 on 2022-09-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financial_assets", "0001_initial"),
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="wallets",
            field=models.ManyToManyField(related_name="assets", to="wallets.wallet"),
        ),
    ]
