# Generated by Django 4.1.1 on 2022-09-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallets", "0001_initial"),
        ("financial_assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="wallets",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assets",
                to="wallets.wallet",
            ),
        ),
    ]
